### ISSUE TITLE
Create State Diagram

### ISSUE THREAD

**Issue by Juxtaposed365** [Juxtaposed365/MercuryMessaging#17]
Here is our state diagram.

**Comment by ayuille1** [comment]
![User_schedule_unschmeeting](https://user-images.githubusercontent.com/55213524/95516783-c54b0980-098d-11eb-8746-170eefee87c3.png)
![User_scheduled_schmeeting](https://user-images.githubusercontent.com/55213524/95516787-c5e3a000-098d-11eb-9855-d97427723d47.png)
![User_msg_multiple_rec](https://user-images.githubusercontent.com/55213524/95516791-c67c3680-098d-11eb-838e-663f5b53f2fa.png)
![User_msg_single_user](https://user-images.githubusercontent.com/55213524/95516796-c714cd00-098d-11eb-89c5-28c1672d262f.png)
![User_multmsg](https://user-images.githubusercontent.com/55213524/95516800-c7ad6380-098d-11eb-80b5-13e4d65e5657.png)
![User_registration_manyapps](https://user-images.githubusercontent.com/55213524/95516802-c845fa00-098d-11eb-9d08-4b01b4753d9d.png)
![User_registration_noapps](https://user-images.githubusercontent.com/55213524/95516804-c8de9080-098d-11eb-82c1-e62520e2e893.png)
![User_registration_oneapp](https://user-images.githubusercontent.com/55213524/95516806-c8de9080-098d-11eb-9498-bfbeda1020a7.png)

Uploaded all state diagrams.
