### ISSUE TITLE
Create Database Schema 

### ISSUE THREAD

**Issue by Juxtaposed365** [Juxtaposed365/MercuryMessaging#4]
We need to create and entity and attribute diagram to provide to team 5 as well as the relationships between the data and the requests we will be making in our code.

**Comment by Juxtaposed365** [comment]
We decided to go with Firestore and created a draw.io file with the schema.

**Comment by Juxtaposed365** [comment]
[MercuryDatabase .pdf](https://github.com/Juxtaposed365/MercuryMessaging/files/5301218/MercuryDatabase.1.pdf)

**Comment by ayuille1** [comment]
[DatabaseTableNotes.txt](https://github.com/Juxtaposed365/MercuryMessaging/files/5325107/DatabaseTableNotes.txt)
![database_recip_numbered](https://user-images.githubusercontent.com/55213524/95038391-f8468200-069b-11eb-915f-63c0ea216317.png)
![database_recip_nokey](https://user-images.githubusercontent.com/55213524/95038392-fa104580-069b-11eb-949a-c92e03486838.png)
![database_recip_key](https://user-images.githubusercontent.com/55213524/95038393-fbda0900-069b-11eb-9b3d-1a5512855f47.png)

**Comment by ayuille1** [comment]
Added three different database examples, and added notes so I could share my thoughts with the team.

**Comment by Juxtaposed365** [comment]
Awesome they look great.

**Comment by ayuille1** [comment]
![database_schema](https://user-images.githubusercontent.com/55213524/95114606-33839800-0712-11eb-9bd8-2cda01e2637c.png)

Presentation ready database diagram
