### ISSUE TITLE
Login to Firestore

### ISSUE THREAD

**Issue by Juxtaposed365** [Juxtaposed365/MercuryMessaging#5]
How can we access the backend of Firestore and how do we connect it to Android Studio?

**Comment by mdiallo09** [comment]
[https://app.zenhub.com/files/294190263/fbc0744b-d6f9-48b8-a845-8356e7b4219b/download](https://app.zenhub.com/files/294190263/fbc0744b-d6f9-48b8-a845-8356e7b4219b/download)
