### ISSUE TITLE
Pull from Firestore

### ISSUE THREAD

**Issue by Juxtaposed365** [Juxtaposed365/MercuryMessaging#6]
How to pull data from the data base to use in our app.

**Comment by mdiallo09** [comment]
[https://app.zenhub.com/files/294190263/9cab9dbb-9c8b-47df-bcfa-0595b3ac9c53/download](https://app.zenhub.com/files/294190263/9cab9dbb-9c8b-47df-bcfa-0595b3ac9c53/download)
