### ISSUE TITLE
Prepopulate example data

### ISSUE THREAD

**Issue by Juxtaposed365** [Juxtaposed365/MercuryMessaging#8]

**Comment by Juxtaposed365** [comment]
Fill the database with example data for team 5 and to use for testing.

**Comment by mdiallo09** [comment]
![Screen Shot 2020-10-05 at 1.28.14 PM.png](https://images.zenhubusercontent.com/5f596b45010d5eecf916d9a2/1405701e-0132-481a-93f7-66353c0a80fc)
